# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: My Website
email: geoffchoy@outlook.com
description: >-
  A little about me and a few thoughts I jot down every so often

baseurl: ""
github_username: burrt
gh_url: "https://burrt.github.io/"

google_analytics: UA-104494941-6

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    name: "Blog Posts"
    site_section: true
    output: true
    permalink: /posts/:path/
    prefix: "/posts"
    selectorName: "posts"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: /assets/img/gchoy-1024x512.png
      height: 512
      width: 1024

# SEO
social:
  name: Geoffrey Choy
  links:
    - https://www.linkedin.com/in/geoffrey-choy

twitter:
  username: gcho300
  card: summary

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
