title: My Website
author: Geoffrey Choy
email: geoffchoy@outlook.com
description: >-
  A little about me and a few thoughts I jot down every so often

baseurl: ""
github_username: burrt
gh_url: "https://burrt.github.io/"

google_analytics: UA-104494941-6

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  posts:
    name: "Blog Posts"
    site_section: true
    output: true
    permalink: /posts/:path/
    prefix: "/posts"
    selectorName: "posts"

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      image: /assets/img/gchoy-1024x512.png
      height: 512
      width: 1024

# SEO
social:
  name: Geoffrey Choy
  links:
    - https://www.linkedin.com/in/geoffrey-choy

twitter:
  username: gcho300
  card: summary

logo: /favicons/favicon-96x96.png

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
